-- local boneNames = {
--     "ValveBiped.Bip01_Pelvis",
--     "ValveBiped.Bip01_Spine",
--     "ValveBiped.Bip01_Spine1",
--     "ValveBiped.Bip01_Spine2",
--     "ValveBiped.Bip01_Spine4",
--     "ValveBiped.Bip01_L_Clavicle",
--     "ValveBiped.Bip01_L_UpperArm",
--     "ValveBiped.Bip01_L_Forearm",
--     "ValveBiped.Bip01_L_Hand",
--     "ValveBiped.Bip01_L_Finger0",
--     "ValveBiped.Bip01_L_Finger01",
--     "ValveBiped.Bip01_L_Finger02",
--     "ValveBiped.Bip01_L_Finger1",
--     "ValveBiped.Bip01_L_Finger11",
--     "ValveBiped.Bip01_L_Finger12",
--     "ValveBiped.Bip01_L_Finger2",
--     "ValveBiped.Bip01_L_Finger21",
--     "ValveBiped.Bip01_L_Finger22",
--     "ValveBiped.Bip01_L_Finger3",
--     "ValveBiped.Bip01_L_Finger31",
--     "ValveBiped.Bip01_L_Finger32",
--     "ValveBiped.Bip01_L_Finger4",
--     "ValveBiped.Bip01_L_Finger41",
--     "ValveBiped.Bip01_L_Finger42",
--     "ValveBiped.Bip01_R_Clavicle",
--     "ValveBiped.Bip01_R_UpperArm",
--     "ValveBiped.Bip01_R_Forearm",
--     "ValveBiped.Bip01_R_Hand",
--     "ValveBiped.Bip01_R_Finger0",
--     "ValveBiped.Bip01_R_Finger01",
--     "ValveBiped.Bip01_R_Finger02",
--     "ValveBiped.Bip01_R_Finger1",
--     "ValveBiped.Bip01_R_Finger11",
--     "ValveBiped.Bip01_R_Finger12",
--     "ValveBiped.Bip01_R_Finger2",
--     "ValveBiped.Bip01_R_Finger21",
--     "ValveBiped.Bip01_R_Finger22",
--     "ValveBiped.Bip01_R_Finger3",
--     "ValveBiped.Bip01_R_Finger31",
--     "ValveBiped.Bip01_R_Finger32",
--     "ValveBiped.Bip01_R_Finger4",
--     "ValveBiped.Bip01_R_Finger41",
--     "ValveBiped.Bip01_R_Finger42",
--     "ValveBiped.Bip01_Neck1",
--     "ValveBiped.Bip01_Head1",
--     "ValveBiped.Bip01_L_Thigh",
--     "ValveBiped.Bip01_L_Calf",
--     "ValveBiped.Bip01_L_Foot",
--     "ValveBiped.Bip01_L_Toe0",
--     "ValveBiped.Bip01_R_Thigh",
--     "ValveBiped.Bip01_R_Calf",
--     "ValveBiped.Bip01_R_Foot",
--     "ValveBiped.Bip01_R_Toe0"
-- }

local boneNames = {
    ["ValveBiped.Bip01_Pelvis"] = true,
    ["ValveBiped.Bip01_Spine"] = true,
    ["ValveBiped.Bip01_Spine1"] = true,
    ["ValveBiped.Bip01_Spine2"] = true,
    ["ValveBiped.Bip01_Spine4"] = true,
    ["ValveBiped.Bip01_L_Clavicle"] = true,
    ["ValveBiped.Bip01_L_UpperArm"] = true,
    ["ValveBiped.Bip01_L_Forearm"] = true,
    ["ValveBiped.Bip01_L_Hand"] = true,
    ["ValveBiped.Bip01_L_Finger0"] = true,
    ["ValveBiped.Bip01_L_Finger01"] = true,
    ["ValveBiped.Bip01_L_Finger02"] = true,
    ["ValveBiped.Bip01_L_Finger1"] = true,
    ["ValveBiped.Bip01_L_Finger11"] = true,
    ["ValveBiped.Bip01_L_Finger12"] = true,
    ["ValveBiped.Bip01_L_Finger2"] = true,
    ["ValveBiped.Bip01_L_Finger21"] = true,
    ["ValveBiped.Bip01_L_Finger22"] = true,
    ["ValveBiped.Bip01_L_Finger3"] = true,
    ["ValveBiped.Bip01_L_Finger31"] = true,
    ["ValveBiped.Bip01_L_Finger32"] = true,
    ["ValveBiped.Bip01_L_Finger4"] = true,
    ["ValveBiped.Bip01_L_Finger41"] = true,
    ["ValveBiped.Bip01_L_Finger42"] = true,
    ["ValveBiped.Bip01_R_Clavicle"] = true,
    ["ValveBiped.Bip01_R_UpperArm"] = true,
    ["ValveBiped.Bip01_R_Forearm"] = true,
    ["ValveBiped.Bip01_R_Hand"] = true,
    ["ValveBiped.Bip01_R_Finger0"] = true,
    ["ValveBiped.Bip01_R_Finger01"] = true,
    ["ValveBiped.Bip01_R_Finger02"] = true,
    ["ValveBiped.Bip01_R_Finger1"] = true,
    ["ValveBiped.Bip01_R_Finger11"] = true,
    ["ValveBiped.Bip01_R_Finger12"] = true,
    ["ValveBiped.Bip01_R_Finger2"] = true,
    ["ValveBiped.Bip01_R_Finger21"] = true,
    ["ValveBiped.Bip01_R_Finger22"] = true,
    ["ValveBiped.Bip01_R_Finger3"] = true,
    ["ValveBiped.Bip01_R_Finger31"] = true,
    ["ValveBiped.Bip01_R_Finger32"] = true,
    ["ValveBiped.Bip01_R_Finger4"] = true,
    ["ValveBiped.Bip01_R_Finger41"] = true,
    ["ValveBiped.Bip01_R_Finger42"] = true,
    ["ValveBiped.Bip01_Neck1"] = true,
    ["ValveBiped.Bip01_Head1"] = true,
    ["ValveBiped.Bip01_L_Thigh"] = true,
    ["ValveBiped.Bip01_L_Calf"] = true,
    ["ValveBiped.Bip01_L_Foot"] = true,
    ["ValveBiped.Bip01_L_Toe0"] = true,
    ["ValveBiped.Bip01_R_Thigh"] = true,
    ["ValveBiped.Bip01_R_Calf"] = true,
    ["ValveBiped.Bip01_R_Foot"] = true,
    ["ValveBiped.Bip01_R_Toe0"] = true
}

return boneNames
